version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2
    hostname: sql2
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NewStrong@Passw0rd"
    ports:
      - "1433:1433"
    networks:
      - sqlnetwork

networks:
  sqlnetwork:
    driver: bridge
